### ISSUE TITLE
解码需求

### ISSUE THREAD

**Issue by BackTrackCRoot** [0Linchen/CTFCrackTools#1]
你好 能不能提供xxcode解码和uucode解码呢？

**Comment by 0Linchen** [comment]
xxcode是什么编码？在网络上找不到关于这款编码的信息，您有资料嘛，请发我一份。
 
 
------------------ Original ------------------
From: "CRoot"; 
Date: 2017年1月2日(星期一) 上午9:43
To: "0Linchen/CTFCrackTools"; 
Cc: "Subscribed"; 
Subject: [0Linchen/CTFCrackTools] 解码需求 (#1)

 

你好 能不能提供xxcode解码和uucode解码呢？

**Comment by BackTrackCRoot** [comment]
XXCode确实是一个很生僻的东西 只有英文维基百科才能查到。
是类UUcode的一种东西
https://en.wikipedia.org/wiki/Xxencoding
之前貌似写过一个Python的解密，容我找找，您先看看这个可以不。

**Comment by 0Linchen** [comment]
其实...如果你已经写过python的话...你可以参照下前面的开发文档....直接编写成插件，然后调用就OK了...或者把这个插件投到我的邮箱，我再接入
